# Capítulo 15. Eigendecomposition (descomposición propia)

La descomposición propia de una matriz (eigendecomposition) es un tipo de descomposición que implica descomponer una matriz cuadrada en un conjunto de vectores propios (eigenvectors) y valores propios (eigenvalues).

Un vector es un vector propio cuando satisface: A · v = λ · v. A esta ecuacion se la llama ecuacion de valor propio (eigenvalue equation), donde A es la matriz cuadrada que estamos descomponiendo, v es el vector porpio de la matriz, y λ es el valor propio.

Una matriz puede tener un vector propio y un valor propio para cada dimension. No todas las matrices se puedes descomponer en vectores y valores propios y algunas solo se pueden descomponer de manera que requieren numeros complejos. La matriz primaria puede mostrarse como un producto de vectores y valores propios. A = Q · Λ · Q <sup>−1</sup>. Donde Q es una matriz compuesta por los vectores propios, Λ (letra griega en mayúscula lambda) es la matriz diagonal compuesta por los valores propios, y Q <sup>-1</sup> es la inversa de la matriz compuesta por los vectores propios.

La descomposición propia (eigendecomposition) puede ser usada para calcular los componentes principales de una matriz en el Análisis de Componentes Principales (Principal Component Analisys, PCA) que puede ser usado para reducir la dimensionalidad de los datos en el aprendizaje automático. Ciertas calculos de matrices, como calcular la potencia de una matriz se facilitan mucho cuando usamos la descomposicion propia de una matriz.

## Vectores y valores propios (Eigenvectors y Eigenvalies)

Los vectores propios son vectores unitarios, lo que significa que su longitud o magnitud es igual a 1.0. A menudo se los denomina vectores derechos, lo que simplemente significa un vector de columna (a diferencia de un vector de fila o un vector izquierdo). Los valores propios son coeficientes aplicados a vectores propios que dan a los vectores su longitud o magnitud. Por ejemplo, un valor propio negativo puede invertir la dirección del vector propio y tambien escalarlo. 

## Cálculo de la descomposición propia

In [1]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig

# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
# factorize
values, vectors = eig(A)

In [3]:
values

array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16])

In [4]:
vectors

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

## Confirmación de vectores y valores propios

Un vector es un vector propio cuando satisface: A · v = λ · v

In [5]:
v = vectors[:, 0]
v

array([-0.23197069, -0.52532209, -0.8186735 ])

In [6]:
# confirm first eigenvector
B = A.dot(v)
B

array([ -3.73863537,  -8.46653421, -13.19443305])

In [7]:
C = values[0] * v
C

array([ -3.73863537,  -8.46653421, -13.19443305])

## Reconstrución de la matriz

Podemos revertir el proceso y reconstruir la matriz original con solo los vectores y los valores propios. Primero, la lista de vectores propios se debe tomar en conjunto como una matriz, donde cada vector se convierte en una fila. Los valores propios deben organizarse en una matriz diagonal. La función diag() se puede usar para esto. A continuación, debemos calcular la inversa de la matriz de vectores propios, que podemos lograr con la función inv(). Finalmente, estos elementos deben multiplicarse con la función dot(). A = Q · Λ · Q <sup>−1</sup>

In [8]:
# reconstruct matrix
from numpy import diag
from numpy.linalg import inv

# create matrix from eigenvectors
Q = vectors
Q

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

In [9]:
# create inverse of eigenvectors matrix
R = inv(Q)
R

array([[-0.48295226, -0.59340999, -0.70386772],
       [-0.91788599, -0.24901003,  0.41986593],
       [ 0.40824829, -0.81649658,  0.40824829]])

In [10]:
# create diagonal matrix from eigenvalues
L = diag(values)
L

array([[ 1.61168440e+01,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.11684397e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -9.75918483e-16]])

In [11]:
# reconstruct the original matrix
B = Q.dot(L).dot(R)
B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])