# Capítulo 14. Descomposición de matrices

La descomposición de una matriz es una manera de reducir una matriz en sus partes constituyentes. Es un enfoque que permite simplificar operaciones de matrices mas complejas que pueden ser ejecutadas en la matriz descompuesta en lugar de la matriz orifinal. También se llama factorización de matrices dado que es como factorizar valores reales pero con matrices.

## Descomposición LU

La descomposicion LU es para matrices cuadradas y descompone una matriz en los componentes L y U. Se define como A = LU donde L es el triángulo inferior de la matriz y U es el triángulo superor de la matriz.

La descomposición LU puede fallar para matrices que no pueden ser descompuestas con facilidad. Una variación mas estable es la descomposición LUP,  o descomposición LU con pivote parcial que se define como A = PLU. Las filas de la matriz padre se reordenan para simplificar el proceso de descomposición y la matriz adicional P especifica una manera de devolver el resultado al orden original.

In [1]:
# LU decomposition
from numpy import array
from scipy.linalg import lu

# define a square matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
# factorize
P, L, U = lu(A)

In [3]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [4]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [5]:
U

array([[ 7.00000000e+00,  8.00000000e+00,  9.00000000e+00],
       [ 0.00000000e+00,  8.57142857e-01,  1.71428571e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.58603289e-16]])

In [6]:
# reconstruct
B = P.dot(L).dot(U)
B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## Descomposición QR

La descomposición QR es para matrices m x n (no se limita a matrices cuadradas) y descompone la matriz en los componentes Q y R. A = QR. Donde Q es una matriz m x m y R es una matriz triángulo superior m x n.

La función qr() de NumPy por defecto devuelve matrices Q y R mas pequeñas, podemos especificar el argumento 'complete' para que devuelva las matrices del tamaño esperado (m x m y m x n).

In [7]:
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])

A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
from numpy.linalg import qr

# factorize
Q, R = qr(A, 'complete')

In [9]:
Q

array([[-0.16903085,  0.89708523,  0.40824829],
       [-0.50709255,  0.27602622, -0.81649658],
       [-0.84515425, -0.34503278,  0.40824829]])

In [10]:
R

array([[-5.91607978, -7.43735744],
       [ 0.        ,  0.82807867],
       [ 0.        ,  0.        ]])

In [11]:
# reconstruct
B = Q.dot(R)
B

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

## Descomposición Cholesky

La descomposición Cholesky es para matrices simétricas cuyos valores son mayores a 0, también llamadas matrices definidas positivas. La descomposición de define como: A = LL<sup>T</sup> donde A es la matriz descompuesta, L es la matriz triangular inferior y L<sup>T</sup> es la matriz traspuesta de L. Esta descomposición tambien se puede definir con la matriz superior triangular: A = U<sup>T</sup>U.

Cuando se descomponen matrices simétricas, la descomposicón Cholesky es cerca del doble de eficiente que la descomposición LU.

In [12]:
# define symmetrical matrix
A = array([
[2, 1, 1],
[1, 2, 1],
[1, 1, 2]])

A

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [13]:
from numpy.linalg import cholesky

# factorize
L = cholesky(A)
L

array([[1.41421356, 0.        , 0.        ],
       [0.70710678, 1.22474487, 0.        ],
       [0.70710678, 0.40824829, 1.15470054]])

In [14]:
# reconstruct
B = L.dot(L.T)
B

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])