# Capítulo 4. Introducción a los arrays NumPy

Los arrays son la principal estructura de datos en el aprendizaje automático. Python tiene una librería para trabajar con arrays de manera eficiente llamada NumPy. Su principal estructura de datos es el `ndarray` que sirve para crear arrays multidimensionales. Es un array con un tamaño fijo en memoria y de un solo tipo.

In [1]:
# array es la principal estructura de datos con la que se trabaja en numpy
from numpy import array

# crea un numpy array desde una lista python
a = array([1.0, 2.0, 3.0])
a

array([1., 2., 3.])

In [2]:
# muestra la dimensión del array
a.shape

(3,)

In [3]:
# muestra el tipo de dato que contienen los elementos del array
a.dtype

dtype('float64')

## Funciones para crear arrays y matrices

Numpy contiene funciones de utilidad para crear arrays y matrices dadas unas dimensiones.

In [4]:
# función para crear arrays vacios
from numpy import empty

# crea una matriz de 3 x 3 con elementos aleatorios a partir de las dimensiones que se le pasan como parametro
a = empty([3,3])
a

array([[4.44389806e+252, 2.32159998e-152, 2.66064968e-260],
       [1.27661731e-152, 6.01334659e-154, 4.47593816e-091],
       [2.12701067e+233, 9.08697697e+223, 1.03819321e-028]])

In [5]:
# funcion para crear arrays de 0s
from numpy import zeros

# crea una matriz de 3 x 5 de 0s a partir de las dimensiones que se le pasan como parametro
a = zeros([3,5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
# funcion para crear arrays de 1s
from numpy import ones

# crea un vector de 5 elementos de 1s
a = ones([5])
a

array([1., 1., 1., 1., 1.])

## Apilar arrays vertical y horizontalmente

Numpy también contiene funciones de utilidad para crear arrays desde arrays existentes.

In [7]:
# function para apilar verticalmente
from numpy import vstack
# funcion para apilar horizontalmente
from numpy import hstack

a1 = array([1,2,3])
a2 = array([4,5,6])

In [8]:
# apila los arrays verticalmente creanto una matriz de 2 x 3
a3 = vstack((a1, a2))
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# dimensión del array
a3.shape

(2, 3)

In [10]:
# apila los arrays horizontalmente creando un vector de los arrays 
a3 = hstack((a1, a2))
a3

array([1, 2, 3, 4, 5, 6])

In [11]:
# dimensión del array
a3.shape

(6,)