# Capítulo 17. Introducción a la estadistica multivariable

## Valor esperado y media

Se puede usar la funcion mean() de NumPy, acepta un segundo parámetro donde se puede definir el eje de la media.

In [1]:
# vector mean
from numpy import array
from numpy import mean

# define vector
v = array([1,2,3,4,5,6])

# calculate mean
result = mean(v)
result

3.5

In [2]:
# define matrix
M = array([
[1,2,3,4,5,6],
[1,2,3,4,5,6]])

# column means
col_mean = mean(M, axis=0)
col_mean

array([1., 2., 3., 4., 5., 6.])

In [3]:
# row means
row_mean = mean(M, axis=1)
row_mean

array([3.5, 3.5])

## Varianza y desviación estándar

En probabilidad, la varianza de alguna variable aleatoria X es una medida de la cantidad de valores en la distribución varían en promedio con respecto a la media. La varianza se denota como la función var() de NumPy.

Por defecto Numpy calcula la varianza de población (population variance), para muesta de varianza (sample variance), deberemos establecer el argumento ddof a 1. Al igual que la función mean() puede calcular la varianza por ejes.

In [4]:
# vector variance
from numpy import var

# calculate variance
result = var(v, ddof=1)
result

3.5

In [5]:
# column variances
col_var = var(M, ddof=1, axis=0)
col_var

array([0., 0., 0., 0., 0., 0.])

In [6]:
# row variances
row_var = var(M, ddof=1, axis=1)

La desviación estándar se calcula usando la raiz cuadrada de la varianza. Al igual que la función var() se debe establecer el argumento ddof a 1 y se puede definir el eje que se desea calcular.

In [7]:
from numpy import std

# column standard deviations
col_std = std(M, ddof=1, axis=0)
col_std

array([0., 0., 0., 0., 0., 0.])

In [8]:
# row standard deviations
row_std = std(M, ddof=1, axis=1)
row_std

array([1.87082869, 1.87082869])