# Capítulo 14. Descomposición de matrices

La descomposición de una matriz es una manera de reducir una matriz en usu partes constituyentes. Es un enfoque que permite simplificar operaciones de matrices mas complejas que pueden ser ejecutadas en la matriz descompuesta en lugar de la matriz orifinal. También se llama factorización de matrices dado que es como factorizar valores reales pero con matrices.

## Descomposición LU

La descomposicion LU es para matrices cuadradas y descompone una matriz en los componentes L y U. A = LU.
L es el triángulo inferior de la matriz y U es el triángulo superor de la matriz.

La descomposición LU puede fallar para matrices que no pueder ser descompuestas con facilidad. Una variación mas estable es la descomposicion LUP,  o descomposición LU con pivote parcial. A = P · L · U. Las filas de la matriz padre se reordenan para simplificar el proceso de descomposición y la matriz adicional P especifica una manera de devolver el resultado al orden original.

In [1]:
# LU decomposition
from numpy import array
from scipy.linalg import lu

# define a square matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
# factorize
P, L, U = lu(A)

In [3]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [4]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [5]:
U

array([[ 7.00000000e+00,  8.00000000e+00,  9.00000000e+00],
       [ 0.00000000e+00,  8.57142857e-01,  1.71428571e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.58603289e-16]])

In [6]:
# reconstruct
B = P.dot(L).dot(U)

B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])