# Capítulo 13. Tensores y aritmetica de tensores

Son una generalización de vectores y matrices, se puede pensar en ellos como un array multidimensional.

Un vector es un tensor de primer orden y una matriz un tensor de segundo orden.

## Creación de tensores

A continuación se definen dos tensores de 3x3x3.

In [1]:
from numpy import array

# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])

# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])

A

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

El tensor se pinta como una serie de matrices, una por cada capa. Para un tensor 3D el eje 0 especifica el 
nivel (altura), el eje 1 especifica la columna y el eje 2 la fila.

In [2]:
A.shape

(3, 3, 3)

## Suma de tensores

Los tensores deben ser del mismo tamaño.

In [3]:
# add tensors
C = A + B

C

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[22, 24, 26],
        [28, 30, 32],
        [34, 36, 38]],

       [[42, 44, 46],
        [48, 50, 52],
        [54, 56, 58]]])

## Resta de tensores

Los tensores deben ser del mismo tamaño

In [4]:
# subtract tensors
C = A - B

C

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

## Multiplicación Hadamard

Los tensores deben ser del mismo tamaño. Esta multiplicación se hace a nivel de cada elemento y se llama Hadamard
para diferenciarla de la multiplicación habitual de tensores. Se usa el operador ◦ para indicar la multiplicación
Hadamard entre tensores. C = A ◦ B

In [5]:
C = A * B

C

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[121, 144, 169],
        [196, 225, 256],
        [289, 324, 361]],

       [[441, 484, 529],
        [576, 625, 676],
        [729, 784, 841]]])

## División de tensores

Los tensores deben ser del mismo tamaño.

In [6]:
C = A / B

C

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## Multiplicación de tensores

La multiplicación de tensores se denota el siguiente simbolo: ⊗ (C = a ⊗ b). Dado un tensor A con q dimensiones y un tensor B con r dimensiones, el producto de estos tensores sera un nuevo tensor de q + r dimesiones. El producto de tensores no esta limitado a tensores de 3 dimensiones, tambien se puede realizar con matrices y vectores.

Para realizar la multiplicación de tensores utilizaremos la función tensordot() de NumPy que tima como argumentos los dos tensores a multiplicar y el eje sobre el que se suman los productos, llamada reducción de suma. Para calcular la multiplicación de tensores, también llamado tensor dot product en NumPy, el eje debe establecerse a 0.

In [7]:
from numpy import tensordot

# define first vector
A = array([1,2])

# define second vector
B = array([3,4])

# calculate tensor product
C = tensordot(A, B, axes=0)

C

array([[3, 4],
       [6, 8]])